name: github-pages
on:
  push:
    branches: [main]
jobs:
  main:
    permissions:
      pages: write
      id-token: write
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx @marp-team/marp-cli README.md -o pages/index.html
      - uses: actions/upload-pages-artifact@v1
        with:
          path: pages
      - uses: actions/deploy-pages@v1
